name: Publish package

on:
  push:
    tags:
      - v*

env:
  node_version: 20
  cache-prefix: codecarrot-essentials

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.6.0

      - name: Build
        run: |
          pnpm i --frozen-lockfile --prod=false
          pnpm build

      - name: Cache 'dist' directory
        uses: actions/cache@v4
        id: cache-build
        with:
          path: |
            ${{ github.workspace }}/dist
          # Generate a new cache whenever packages or source files change.
          key: |
            ${{ env.cache-prefix }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-prefix }}-${{ github.sha }}

  publish-npm:
    name: "Publish to NPM"
    if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.6.0

      - name: Cache 'dist' directory
        uses: actions/cache@v4
        id: cache-build
        with:
          path: |
            ${{ github.workspace }}/dist
          key: |
            ${{ env.cache-prefix }}-${{ github.sha }}
          restore-keys: |
            ${{ env.cache-prefix }}-${{ github.sha }}

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.PKG_NPM_TOKEN}}

      - run: |
          pnpm publish --no-git-checks --access=public
